# Generated by Django 6.0.3 on 2026-04-17 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(choices=[('books', 'Books'), ('electronics', 'Electronics'), ('cycles', 'Cycles'), ('kitchen', 'Kitchen Appliances'), ('hostel_essentials', 'Hostel Essentials'), ('furniture', 'Furniture'), ('other', 'Other')], max_length=50)),
                ('condition', models.CharField(choices=[('new', 'Like New'), ('good', 'Good'), ('fair', 'Fair'), ('used', 'Used')], default='good', max_length=20)),
                ('location_type', models.CharField(choices=[('hostel', 'Hostel'), ('day_scholar', 'Day Scholar')], max_length=20)),
                ('hostel_name', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ManyToManyField(blank=True, related_name='wishlist_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
